name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - uses: nttld/setup-ndk@v1
        id: ndk
        with:
          ndk-version: r26b

      - run: sudo apt-get update && sudo apt-get install -y ninja-build

      - name: decoder_av1 - cpu_features
        uses: actions/checkout@v4
        with:
          repository: google/cpu_features
          ref: v0.9.0
          path: libraries/decoder_av1/src/main/jni/cpu_features

      - name: decoder_av1 - libgav1
        uses: actions/checkout@v4
        with:
          repository: moneytoo/libgav1
          ref: v0.20.0
          path: libraries/decoder_av1/src/main/jni/libgav1

      - name: decoder_av1 - abseil
        uses: actions/checkout@v4
        with:
          repository: abseil/abseil-cpp
          ref: 20230802.1
          path: libraries/decoder_av1/src/main/jni/libgav1/third_party/abseil-cpp

      - name: decoder_mpegh
        uses: actions/checkout@v4
        with:
          repository: Fraunhofer-IIS/mpeghdec
          ref: r2.0.1
          path: libraries/decoder_mpegh/src/main/jni/libmpegh

      - name: decoder_iamf
        uses: actions/checkout@v4
        with:
          repository: AOMediaCodec/libiamf
          ref: v1.1.0
          path: libraries/decoder_iamf/src/main/jni/libiamf
          sparse-checkout: |
            *
            !tests/
          sparse-checkout-cone-mode: false

      - name: decoder_ffmpeg
        uses: actions/checkout@v4
        with:
          repository: FFmpeg/FFmpeg
          ref: release/6.0
          path: libraries/decoder_ffmpeg/src/main/jni/ffmpeg

      - run: ./build_ffmpeg.sh
          ${{ github.workspace }}/libraries/decoder_ffmpeg/src/main
          ${{ steps.ndk.outputs.ndk-path }}
          $(uname -s | tr '[:upper:]' '[:lower:]')-x86_64
          21
          vorbis opus flac alac pcm_mulaw pcm_alaw mp3 amrnb amrwb aac ac3 eac3 dca mlp truehd
        working-directory: libraries/decoder_ffmpeg/src/main/jni

      - run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > ${GITHUB_WORKSPACE}/keystore.jks

      - run: ./gradlew assembleRelease
          -Pandroid.injected.signing.store.file=${GITHUB_WORKSPACE}/keystore.jks
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }}
          -Pandroid.injected.signing.key.alias=key
          -Pandroid.injected.signing.key.password=${{ secrets.KEYSTORE_PASSWORD }}

      - uses: actions/upload-artifact@v4
        with:
          name: libraries
          path: ${{ github.workspace }}/libraries/*/buildout/outputs/aar/*-release.aar

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/demos/*/buildout/outputs/apk/*/release/*.apk
            ${{ github.workspace }}/demos/*/buildout/outputs/apk/release/*.apk
          prerelease: true
          draft: true
